name: Build and Test

on:
  push:
    branches:
      - master # 只在 master 分支上推送代码时运行工作流

jobs:
  build-and-test:

    runs-on: ubuntu-latest # 在 Ubuntu 操作系统上运行工作流

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 使用官方的 checkout 动作，拉取代码

      - name: Setup Node.js
        uses: actions/setup-node@v2 # 使用官方的 Node.js 设置动作，安装 Node.js

      - name: Install dependencies
        run: npm install # 安装项目依赖项

      - name: Build project
        run: npm run build # 构建项目

      - name: Run tests
        run: npm test # 运行测试

      - name: Build and Push Docker Image
        run: $GITHUB_WORKSPACE/ci/gen-image.sh
      #        uses: mr-smithers-excellent/docker-build-push@v4
      #        with:
      #          image: siyustarla/todolist-frontend
      #          registry: docker.io
      #          username: ${{ secrets.DOCKER_USERNAME }}
      #          password: ${{ secrets.DOCKER_PASSWORD }}
      #          tags: siyustarla/todolist-frontend:$(date +%Y-%m-%d-%H-%M-%S)


      - name: Send notification on success
        if: success()
        run: echo "success"

